WHITESPACE = _{ " " | "\t" | "\r" | "\n" }
value = ${ "\"" ~ inner ~ "\"" }

inner = @{ char* }

char = {
    !("\"" | "\\") ~ ANY
    | "\\" ~ ("\"" | "\\" | "/" | "b" | "f" | "n" | "r" | "t")
    | "\\" ~ ("u" ~ ASCII_HEX_DIGIT{4})
}

property = ${ASCII_ALPHANUMERIC+}

conditional = {ANY_OF | ALL_OF}

ANY_OF = {"ANY OF"}
ALL_OF = {"ALL OF"}

tag = {value}

expression = { "IF" ~ property ~ conditional ~ value* ~ "TAG" ~ tag* ~ ";"? ~ NEWLINE?}

rules = { SOI ~ (expression)* ~ EOI}